### ISSUE TITLE
Coleco vision not working on TrimUI Smart Pro

### ISSUE THREAD

**Issue by ByronJK** [wsoltys/mist-cores#16]
On the Trimui Smart Pro the Colecovision emulator isn't loading games that are located in it's folder. On the device is registers the amount of games present and when trying to load a game there is only the bezels that appear. tried to update the RetroArch and add the databases and  Machines into the Bios. Is there a  step by step way to get coleco games to work?

**Comment by wsoltys** [comment]
I'm sorry but I don't know what you're talking about :)
RetroArch is a software emulator and this cores are for fpgas and do hardware emulation. Further more this cores are all obsolete and for the MiST system you should have a look at https://github.com/mist-devel/mist-board/wiki
